---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
# DataVisuals


--
## Index

- Tips
- Environment
- Examples



## TIPS
 
- RStudio Notebook Shortcuts
  - Insert new code: *Ctrl+Alt+I* OR "Insert" button
  - Execute code: *Ctrl+Shift+Enter* OR "Run" button
  - Preview notebook: *Ctrl+Shift+K* OR "Preview" button

## Environment

```{r}

## import
library(readr)
library(ggplot2)
library(datasets)

## install if import fails
# required_packages <- c("datasets", "ggplot2", "readr")
# install.packages(required_packages)
```



## Examples


### STOCK PRICES OHLC

#### Import Data

```{r}
library(readr)
nifty50 <- read_csv("~/Desktop/Projects/ZNevzz/DataVisuals/data/nifty50.csv")
nifty50

# data <- nifty50[sample(nrow(nifty50), 3000),]
data <- nifty50[1:1000,]
```

#### Initialize plot

```{r}

plot1 <- ggplot(data = data,
          mapping = aes(x = date, y = close))
plot1
```

#### Plot points

        
```{r}
plot11 <- plot1 +
          geom_point()
plot11  
```


---


### AIR QUALITY

```{r}
data <- airquality
```

```{r}
ggplot(data = data, mapping = aes(x=Month, y=Ozone)) + geom_count()
```
```{r}
ggplot(data = data, mapping = aes(x=Month, y=Wind)) + geom_col()
```


### datasets
```{r}
help(datasets)
display <- function(frame) {
  str(frame)
  plot(frame)
}
```


```{r}

applied <- lapply(list(cars, airmiles, AirPassengers, airquality), display)

```
